# set datasource
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      settings:
        trace: true

# mybatis 설정
# 여러개의 TypeHandler 를 등록하려면 결국 config.xml 파일을 이용해야 한다. (여러개의 TypeHandler를 등록하는 옵션이 없다.)
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

# log
logging:
  level:
    org.hibernate: debug
